### ISSUE TITLE
How does it associate with iRule files?

### ISSUE THREAD

**Issue by lrhazi** [bitwisecook/vscode-iRule#1]
Is this enabled on .tcl files ?

**Comment by bitwisecook** [comment]
It associates with extensions inside package.json:

https://github.com/bitwisecook/vscode-iRule/blob/master/package.json#L43

**Comment by bitwisecook** [comment]
If it's a popular request to remove `.tcl` as an association please re-open this ticket and +1 here, if I get a at least a few votes for it I'll remove it.

**Comment by lrhazi** [comment]
Thank you!

**Comment by bitwisecook** [comment]
You're welcome
