### ISSUE TITLE
Seeing language error when editing irules

### ISSUE THREAD

**Issue by DumpySquare** [bitwisecook/vscode-iRule#14]
in the vscode-f5-fast extension, I can open an irule as a tcl/tmos object, like the following:

https://marketplace.visualstudio.com/items?itemName=DumpySquare.vscode-f5-fast

```
ltm rule /Common/app3_rule2 {
#comment

when HTTP_REQUEST {
    # test 444
}
}
```

I get the following error, "`when` missing an explicit priority, add an explicit `priority`";  
![image](https://user-images.githubusercontent.com/3260966/94822157-fcd31800-03c7-11eb-987c-5032cf213b80.png)

The error seems to indicate an update might be needed to the language engine

VSCode details:
>Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by bitwisecook** [comment]
This is just a built in diagnostic warning that the event lacks an explicit priority, use something like `when HTTP_REQUEST priority 500 { ...` or turn off the diagnostic.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/2267430/94838087-fadf7800-040c-11eb-9f61-bb0ff3717abf.png">
