### ISSUE TITLE
Editor sees closing brace as not commented out if preceded by more than one #

### ISSUE THREAD

**Issue by brainfever** [bitwisecook/vscode-iRule#24]
Probably not a big deal unless you find yourself working with some ancient irule with lots of comment blocks, but if there is more than one octothorp in front of a closing brace, the editor no longer sees the closing brace as being commented out.

```tcl
if {$status eq ""} {
    ##}
}
```

VS Code version 1.71.0
F5 Networks iRules v1.6.14

**Comment by bitwisecook** [comment]
Interesting, I'll try to find some time to look at this in the next few weeks.

**Comment by bitwisecook** [comment]
fixed in 1.6.16
