### ISSUE TITLE
Code folding not available on ltm rule

### ISSUE THREAD

**Issue by Domoninic** [bitwisecook/vscode-iRule#25]
This extension seems to assume that a file will have a single irule made up of when {} blocks.
I am often working with multiple rules per file and it would be advantageous to be able to fold based on "ltm rule" but this does not seem to be recognized as a irule command. I know technically it is a TMOS command but it is irule related is a very strong way

**Comment by bitwisecook** [comment]
I've added support for multiple irules in 1.6.18, though I'm not sure nested folding is working correctly and I can't really see where I've gone wrong there.

Please test out the update, I've just pushed it to the extension store.

**Comment by bitwisecook** [comment]
I figured it out, the folding config was in the wrong place, place let me know if this fixes your issues!

**Comment by Domoninic** [comment]
That is working now.
Thanks.

**Comment by bitwisecook** [comment]
glad to hear it
