### ISSUE TITLE
Option to allow selfsigned certs or disable some checks

### ISSUE THREAD

**Issue by joe-belliveau-WD** [bitwisecook/vscode-iRule#31]
SSL Errors is using self signed certificates
to reproduce
  -> create an f5 use a self signed cert from the appliance for the management interface
    -> bind the cert to interface
    -> add the device to the f5 module list
    -> Try to connect

 cause: [Error: write EPROTO 1305672610496:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:231:

**Comment by DumpySquare** [comment]
Hi @joe-belliveau-WD , are you sure these issues are not intended for the vscode-f5 extension?

https://github.com/f5devcentral/vscode-f5

This vscode-irule extension is just for irule support.  I don't think it makes any api calls

**Comment by joe-belliveau-WD** [comment]
It looks like indeed it is, closing issues.
