### ISSUE TITLE
Add a virtual filesystem

### ISSUE THREAD

**Issue by bitwisecook** [bitwisecook/vscode-iRule#4]
https://github.com/microsoft/vscode-extension-samples/tree/master/fsprovider-sample

**Comment by bitwisecook** [comment]
work is ongoing in the [vfs branch](/bitwisecook/vscode-iRule/tree/vfs)

**Comment by bitwisecook** [comment]
It's up to the point that it can load and save iRules on a single BIG-IP, but still needs

- [ ] support manual save and ability to disable autosave
- [ ] properly abstract the API calls
- [ ] support connecting to more than one BIG-IP
- [ ] not require manual configuration (pop up hostname/username/password inputs)
- [ ] support BIG-IQ
- [ ] move how the URLs are done to storing the information with the file/directory objects
- [ ] change to using paging to fetch the objects
- [ ] be more async everywhere

**Comment by DumpySquare** [comment]
It looks like this is the beginning of getting this vscode extension to connect to bigips for irule modification, like the original https://github.com/f5devcentral/f5-irule-editor.  If that is true, this is awesome.  I want in!
