### ISSUE TITLE
Request to add config to disable "problem" checking

### ISSUE THREAD

**Issue by nomaed** [bitwisecook/vscode-iRule#5]
Currently, when there's a `when` block without priority, there's a squiggly line saying that explicit priority is expected. However, this is not really a requirement, nor it is a common practice (AFAIK).
![Screen Shot 2019-09-26 at 10 57 48](https://user-images.githubusercontent.com/9551921/65669593-83824600-e04c-11e9-881a-95286c47a66d.png)

This is just an example.

Would it be possible to add these validations as part of settings? I would like to disable this, or other specific validations, optionally.

**Comment by timriker** [comment]
Ah! found it. Thanks for adding this.

Go to extensions, then pick the extension and use the gear icon to edit the defaults.
