### ISSUE TITLE
Several incorrect indentation cases when formatting file

### ISSUE THREAD

**Issue by nomaed** [bitwisecook/vscode-iRule#8]
I noticed several issues with auto-formatting and how indentation looks after that:

1. `} elseif` that starts on the same line as the closing bracket of previous `if` or `elseif` condition breaks the detection of end of statement and previous block is not un-indented

Before:
```tcl
proc tmp {} {
    if {$a} {
        puts foo
    } elseif {$b} { puts bar }
    else { puts baz }
}

# after formatting:
proc tmp {} {
    if {$a} {
        puts foo
        } elseif {$b} { puts bar }
        else { puts baz }
    }
```
Looks like this happens with mixed closing bracket syntaxes, because when all are using same pattern, formatting is fine:
```tcl
proc tmp {} {
    if {$a} { puts foo }
    elseif {$b} { puts bar }
    else { puts baz }
}
# or
proc tmp {} {
    if {$a} {
        puts foo
    } elseif {$b} {
        puts bar
    } else {
        puts baz
    }
}
```

2. Probably related to the first point:
```tcl
proc escape {value} {
    return [string map {
        "\\"	"\\\\"
        "/"		"\\/"
        "\""	"\\\""
    } $value]
}

# after formatting:
proc escape {value} {
    return [string map {
        "\\"	"\\\\"
        "/"		"\\/"
        "\""	"\\\""
        } $value]
    }
```

3. Multi-line `if` conditions: condition expressions (inside brackets) are always starting on the same column as the main `if` block, instead of being indented:
```tcl
if {aaa &&
    (bbb || ccc)} {
    puts "cool"
}

# after formatting:
if {aaa &&
(bbb || ccc)} {
    puts "cool"
}
```

**Comment by bitwisecook** [comment]
I presume you feel the inputs are correctly formatted?

The long term fix for this will be when I make a proper LSP for it and understand the AST instead of using a bunch of janky regex to do per-line fixes. For now though we should add tests and fix them for these examples, but the current engine can only change the indentation per-line, nothing else.

Where we'll be with the LSP is something like

```tcl
proc tmp {} {
    if {$a} {
        puts foo
    } elseif {$b} { puts bar }
    else { puts baz }
}

# becomes

proc tmp {} {
    if {$a} {
        puts foo
    } elseif {$b} {
        puts bar
    } else {
        puts baz
    }
}
```

**Comment by bitwisecook** [comment]
I absolutely hate that

```
proc tmp {a b} {
    if {$a} {
        puts foo
    } elseif {$b} { puts bar }
    else { puts baz }
}
```

is not valid Tcl but is a valid iRule.

```
tclsh8.4
% proc tmp {a b} {
    if {$a} {
        puts foo
    } elseif {$b} { puts bar }
    else { puts baz }
}
% tmp 0 0
invalid command name "else"
%
```

Yet in an iRule (with `return` rather than `puts`) it compiles and executes just fine.

**Comment by nomaed** [comment]
I am very surprised to read that the first sample is not a valid TCL.

I guess that in essence, `if` is a command that accepts variable number of arguments, some of them can be `else` or `elseif`, but it all has to be a single command, so the only newlines are allowed inside of the curly brackets?

**Comment by nomaed** [comment]
There's another small thing I noticed now after getting the latest version:
```tcl
set val1 [some_func aaa bbb ccc
	ddd eee fff]

set val2 [some_func aaa bbb ccc \
	ddd eee fff]
```
becomes:
```tcl
set val1 [some_func aaa bbb ccc
ddd eee fff]

set val2 [some_func aaa bbb ccc \
	ddd eee fff]
```

With the first setter, line break is valid inside the brackets, so it should be indented, but after formatting the 2nd line (`ddd ...`) has no indentation.
It works fine with the backslash at the end of the line, even though the backslash is not required for a valid tcl syntax.

This problem is not happening with proc params in curly braces, it is being formatted correctly with and without backslash:
```tcl
proc aaa { aa bb cc
	dd ee } { }
# same as
proc aaa { aa bb cc \
	dd ee } { }
```

**Comment by nomaed** [comment]
I see that the proc args works correctly without the backslash as a side-effect of the UglyIf2
